### ISSUE TITLE
TypeError: Cannot read property 'backgroundType' of undefined

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#13]
https://sentry.io/space-babies-bv/scrollytelling/issues/344563398/

```
TypeError: Cannot read property 'backgroundType' of undefined
  at i (/assets/pageflow/application-2779f5ec8e741bf97033b57de4661c87120bafaf864b9940e705fb777f349290.js:42:27362)
  at r.render (/assets/pageflow/application-2779f5ec8e741bf97033b57de4661c87120bafaf864b9940e705fb777f349290.js:28:6817)
  at f._renderValidatedComponentWithoutOwnerOrContext (/assets/pageflow/application-2779f5ec8e741bf97033b57de4661c87120bafaf864b9940e705fb777f349290.js:28:13231)
  at f._renderValidatedComponent (/assets/pageflow/application-2779f5ec8e741bf97033b57de4661c87120bafaf864b9940e705fb777f349290.js:28:13443)
  at f._updateRenderedComponent (/assets/pageflow/application-2779f5ec8e741bf97033b57de4661c87120bafaf864b9940e705fb777f349290.js:28:12674)
...
(27 additional frame(s) were not displayed)
```

**Comment by tilsammans** [comment]
I think this one was caused by the malfunctioning server too.

When Sentry registers this again I might reopen.
