### ISSUE TITLE
TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#17]
https://sentry.io/space-babies/scr/issues/350527811/

```
TypeError: Cannot read property 'parentNode' of undefined
  at f (/assets/pageflow/editor-9049711961ead539886f4de3a14ebe8cf36d348394ba527a698debc63ecf5acf.js:21:7949)
  at b.undoToTextNode (/assets/pageflow/editor-9049711961ead539886f4de3a14ebe8cf36d348394ba527a698debc63ecf5acf.js:21:11556)
  at b.undoToRange (/assets/pageflow/editor-9049711961ead539886f4de3a14ebe8cf36d348394ba527a698debc63ecf5acf.js:21:12875)
  at b.toggleRange (/assets/pageflow/editor-9049711961ead539886f4de3a14ebe8cf36d348394ba527a698debc63ecf5acf.js:21:14045)
  at Object.exec (/assets/pageflow/editor-9049711961ead539886f4de3a14ebe8cf36d348394ba527a698debc63ecf5acf.js:21:23072)
...
(6 additional frame(s) were not displayed)
```

**Comment by tilsammans** [comment]
The breadcrumbs in Sentry reveal nothing out of the ordinary. Previous click was `div > div.configuration_editor > div.input.page_subtitle > input[type="text"]`. The editor told me that the interface was stuck and they refreshed the page.

Possibly an edge case but one line above the exception is wysihtml5. I wonder if our planned upgrade would fix this problem too. We're quite out-dated as it is. /cc @tf

**Comment by tf** [comment]
> I wonder if our planned upgrade would fix this problem too.

Pageflow 12 unfortunately does not change anything about wysihtml5  if that's what you mean.

**Comment by tilsammans** [comment]
True, but this is something I had planned for myself. Actually thought it was a pull request already. I will see if I can get started on that.

**Comment by tilsammans** [comment]
WIP https://github.com/scrollytelling/pageflow/tree/wysihtml-0-6-0

**Comment by tilsammans** [comment]
Discussion about wysihtml will move to codevise/pageflow.
