### ISSUE TITLE
Could not find widget type with name "pageflow_oembed"

### ISSUE THREAD

**Issue by tilsammans** [scrollytelling/app#24]
https://sentry.io/space-babies/scr/issues/403874220/

```
Stacktrace (most recent call first):

  at captureException (raven.js:491:27)
  at wrapped (raven.js:389:22)

Could not find widget type with name "pageflow_oembed"
```

**Comment by tilsammans** [comment]
This happens because existing widgets are not cleaned from the database.

We need to do `Pageflow::Widget.where(role: "oembed", type_name: "pageflow_oembed")` and destroy them all. And add this to the documentation for WidgetType.

**Comment by tilsammans** [comment]
Ran the script manually.
